version: "3.8"

services:
    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        - MYSQL_DATABASE=youssef_DB
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
    achat:
      depends_on:
        - mysqldb
      image: youssef1321/achat:1.0
      restart: on-failure
      ports:
        - "8082:8082"
      environment:
        SERVER_SERVLET_CONTEXT_PATH: /SpringMVC
        SERVER_PORT: 8082
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/youssef_DB??createDatabaseIfNotExists=true
        SPRING_DATASOURCE_USERNAME: root
volumes:
  db: