version: '3'
services:
  backend:
    image: backend
    container_name: backend
    ports:
      - "8089:8089"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /SpringMVC
      SERVER_PORT: 8089
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
