version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
  cadvisor :
    image: google/cadvisor:latest
    ports :
      - 8040:8040
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  achat-app:
    image: hedi1708/achat-1.0:1.2
    container_name: achat-app
    ports:
      - "8089:8089"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/SpringMVC
      - SERVER_PORT=8089
      - SPRING_DATASOURCE_URL=jdbc:mysql://achat-db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=achatuser
      - SPRING_DATASOURCE_PASSWORD=achatpass
    depends_on:
      - achat-db

  achat-db:
    image: mysql:latest
    container_name: achat-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: achatdb
      MYSQL_USER: achatuser
      MYSQL_PASSWORD: achatpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
