version: "3.8"

services:
    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        - MYSQL_DATABASE=youssef_DB
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
    achat:
      depends_on:
        - mysqldb
      image: youssef1321/achat:latest
      restart: on-failure
      ports:
        - "8082:8082"
      environment:
        SERVER_SERVLET_CONTEXT_PATH: /SpringMVC
        SERVER_PORT: 8089
        SPRING_DATASOURCE_URL:  jdbc:mysql://mysqldb:3306/youssef_DB?createDatabaseIfNotExists=true
        SPRING_DATASOURCE_USERNAME: root
volumes:
  db: