version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  achat-app:
    image: benlazreg/achat-app:1.0
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "SPRING_DATASOURCE_URL": jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true"
        "SPRING_DATASOURCE_USERNAME": "root"
        "SPRING_DATASOURCE_PASSWORD": null  # Utilisez le même que MYSQL_ROOT_PASSWORD si root est utilisé
        "SPRING_JPA_HIBERNATE_DDL-AUTO": "update"
        "SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT": "org.hibernate.dialect.MySQL5InnoDBDialect"
      }'
    stdin_open: true
    tty: true
volumes:
  db :